"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const chromeManifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const firefoxManifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.firefox.json"), "utf8"));
assert.equal(chromeManifest.manifest_version, 3);
assert.equal(chromeManifest.background.service_worker, "background/runtime-overrides.js");
assert.equal(chromeManifest.side_panel.default_path, "sidepanel/index.html");
assert(chromeManifest.permissions.includes("offscreen"));
assert.equal(firefoxManifest.manifest_version, 3);
assert.equal(firefoxManifest.background.page, "background/firefox-page.html");
assert.equal(firefoxManifest.sidebar_action.default_panel, "sidepanel/index.html");
assert(!firefoxManifest.permissions.includes("offscreen"));
assert(!firefoxManifest.permissions.includes("sidePanel"));
assert(firefoxManifest.browser_specific_settings.gecko.id);
assert(fs.existsSync(path.join(root, firefoxManifest.background.page)));
const background = fs.readFileSync(path.join(root, "background", "service-worker.js"), "utf8");
const runtime = fs.readFileSync(path.join(root, chromeManifest.background.service_worker), "utf8");
const firefoxPage = fs.readFileSync(path.join(root, firefoxManifest.background.page), "utf8");
assert(runtime.includes('importScripts("service-worker.js")'), "Chrome runtime wrapper must load the privacy core worker");
assert(runtime.includes("compactPlannerContext"), "runtime wrapper must install the planner budget");
assert(firefoxPage.includes('src="agent-runtime.js"') && firefoxPage.includes('src="runtime-overrides.js"'), "Firefox background page must install the same runtime overrides");
assert(background.includes("StrawHatsBrowserAdapter"));
assert(!background.includes("chrome.sidePanel"));
assert(!background.includes("chrome.offscreen"));
assert(fs.readFileSync(path.join(root, "background", "chrome-adapter.js"), "utf8").includes("chrome.offscreen.createDocument"));
assert(fs.readFileSync(path.join(root, "background", "firefox-adapter.js"), "utf8").includes("chrome.sidebarAction.toggle"));
console.log("browser packaging tests passed");
